### ISSUE TITLE
some problems about the link about trained model file

### ISSUE THREAD

**Issue by NIT-JJH** [JosephChenHub/DPANet#1]
Hello sir
        I checked your paper and find your work is a wonderful work! But I found that the link about the trained model file is dead.
So, could you update the link?

**Comment by JosephChenHub** [comment]
> Hello sir
> I checked your paper and find your work is a wonderful work! But I found that the link about the trained model file is dead.
> So, could you update the link?

Hi, due to the crash problem of the server, I lost the trained model and the data is recovering (hope it can be back). If the data cannot be recovered, I will train a new model again.

**Comment by JosephChenHub** [comment]
> Hello sir
> I checked your paper and find your work is a wonderful work! But I found that the link about the trained model file is dead.
> So, could you update the link?

Hi, I have updated the [link](https://drive.google.com/file/d/1bXERDgTKfzkZfXKs8z5vj1QNM3zL-QTL/view), and now you can test the model.
