### ISSUE TITLE
Where is the pseudo label?

### ISSUE THREAD

**Issue by J-JunChen** [JosephChenHub/DPANet#4]
Hi, @JosephChenHub . Thanks for your opensource code.

I would like to know how can I generate the pseudo lable g to learn the potentiality of the depth map? 

Wish you can reply me soon~

**Comment by JosephChenHub** [comment]
> Hi, @JosephChenHub . Thanks for your opensource code.
> 
> I would like to know how can I generate the pseudo lable g to learn the potentiality of the depth map?
> 
> Wish you can reply me soon~

Hi Jun, as described in the `README.md/Prepration` :
```
[optional] generate the pseudo label (provided for NJUD and NLPR) using the scripts gen.m and cal_score.py.
```

**Comment by J-JunChen** [comment]
> > Hi, @JosephChenHub . Thanks for your opensource code.
> > I would like to know how can I generate the pseudo lable g to learn the potentiality of the depth map?
> > Wish you can reply me soon~
> 
> Hi Jun, as described in the `README.md/Prepration` :
> 
> ```
> [optional] generate the pseudo label (provided for NJUD and NLPR) using the scripts gen.m and cal_score.py.
> ```

All right, Thanks~
