### ISSUE TITLE
想用下对比算法的显著图，尤其是poolnet的预测图,能否麻烦您提供下，非常感谢

### ISSUE THREAD

**Issue by StormArcher** [JosephChenHub/DPANet#5]

**Comment by JosephChenHub** [comment]
> _No description provided._

Hi， thanks for your attention, I have updated the link as described in
 

> `The saliency maps of the competitors (official maps or obtained by running the official code) are provided ([Google drive](https://drive.google.com/file/d/1SEhDaiIVJJccv7dIlpk_rp0KZhWab8ie/view?usp=sharing)).`

**Comment by StormArcher** [comment]
thank you
