### ISSUE TITLE
Normalize of the depth image

### ISSUE THREAD

**Issue by Icecream-blue-sky** [JosephChenHub/DPANet#6]
When normalize the depth image, why set self.d_mean = 116.09, self.d_std = 56.61? How do you caculate this? Thanks!

**Comment by JosephChenHub** [comment]
> When normalize the depth image, why set self.d_mean = 116.09, self.d_std = 56.61? How do you caculate this? Thanks!

Hi, you can find that we only normalize the depth map by dividing 255 in the definition of `Normalize`, that means the `self.d_mean` and `self.d_std` are not used.
